### ISSUE TITLE
onMeasure() issue

### ISSUE THREAD

**Issue by jjhesk** [DMCApps/NavigationFragment#12]
Followed by #10. When the animation for the transition from navigation fragment A to B will constantly trigger the mehod `onMeasure` inside the  `SwipeRefreshLayout` until it stop. And this happens when the previous navigation fragment contains `SwipeRefreshLayout` in the page. This will happen in both type of fragments navigationfragment or the singlestackfragmentmangerfragment.  I will have to reproduce this issue exactly on the fork. Is there a way to cancel the animation for all the navigationfragments and try again?

**Comment by jjhesk** [comment]
after the investigation. I think there should be a call back for the viewpager to initiailze with all fragment is completed prepared. #13 shown in the library

**Comment by DMCApps** [comment]
Sorry is this a change that is required? What callback are you implying. I feel like the usecase is specific to the `ViewPager` and since the `NavigationManagerFragment` has no way of telling the views that you are using it should be implemented as needed. The Manager has no clue (nor a way of telling) the type of views that you are using on your `Fragment` and hence can't perform specific actions based on your view choices. The most it works with is presenting and dismissing as well as some basic wrapper work to help with the ActionBar so you don't have to call `getActivity`/`getSupportActionBar` etc.. The communication between fragments is independent of this library and can be resolved through callbacks not handled by the manager.

**Comment by jjhesk** [comment]
if you would checked out the viewpager or the smarttablayout implementations, there were some flashes happened once entering the view.

**Comment by jjhesk** [comment]
finally I have just discovered something related to optical bounds from when the measurements involves in cache
 /**
     \* Sets the measured dimension without extra processing for things like optical bounds.
     \* Useful for reapplying consistent values that have already been cooked with adjustments
     \* for optical bounds, etc. such as those from the measurement cache.
     *
     \* @param measuredWidth The measured width of this view.  May be a complex
     \* bit mask as defined by {@link #MEASURED_SIZE_MASK} and
     \* {@link #MEASURED_STATE_TOO_SMALL}.
     \* @param measuredHeight The measured height of this view.  May be a complex
     \* bit mask as defined by {@link #MEASURED_SIZE_MASK} and
     \* {@link #MEASURED_STATE_TOO_SMALL}.
     */

``` java
    private void setMeasuredDimensionRaw(int measuredWidth, int measuredHeight) {
        mMeasuredWidth = measuredWidth;
        mMeasuredHeight = measuredHeight;

        mPrivateFlags |= PFLAG_MEASURED_DIMENSION_SET;
    }
```

**Comment by jjhesk** [comment]
ok i finally found the location of the bug. it has something to deal with the URV where the setup was wrong and it caused alot of issue around with it. I finally had corrected the order of the setup executions for this type of recyclerview

``` java

    protected void renderviewlayout(View view) throws Exception {
        listview_layout = (UltimateRecyclerView) view.findViewById(getUltimate_recycler_viewResId());
        listview_layout.setHasFixedSize(true);
        listview_layout.setSaveEnabled(false);
        mPicasso = Picasso.with(getActivity());
        mAdapter = new cateadapter(getSourceList());
        setUltimateRecyclerViewExtra(listview_layout, mAdapter);
        mLayoutManager = new LinearLayoutManager(getActivity());
        listview_layout.setLayoutManager(mLayoutManager);
        final HorizontalDividerItemDecoration decor = new HorizontalDividerItemDecoration
                .Builder(getActivity())
                .paint(get_solid())
                .showLastDivider()
                .build();
        listview_layout.addItemDecoration(decor);
        listview_layout.setAdapter(mAdapter);
    }
```

please notice that you have to making sure that `listview_layout.setAdapter(mAdapter);` have to be the last line in the setup and the linearlayoutmanager got to always setup for both savestate null and not null.

**Comment by DMCApps** [comment]
Nice find! I really appreciate all the effort you are putting into making this work! 

Does this also clean up #5 and #10 as these issues are all linked?

**Comment by jjhesk** [comment]
@DMCApps yes, handsomely.
