### ISSUE TITLE
v0.1.3.1

### ISSUE THREAD

**Issue by jjhesk** [DMCApps/NavigationFragment#17]
is this a stable release?

**Comment by DMCApps** [comment]
yes sir. I have been using it in my applications for the past 2 weeks without issue. 

Anything pushed to the master branch and tagged can be considered stable. All development will take place on the 'develop' branch until stable and then it will be pushed to the master and tagged for release.

I haven't had much spare time to work on this. I'll be back at it again hopefully by next week!

Enjoy and let me know if anything comes up that needs fixing I'll see if I can slot in some time
