### ISSUE TITLE
not able to handle restorestate

### ISSUE THREAD

**Issue by jjhesk** [DMCApps/NavigationFragment#21]
This has been consistently triggered. 

```
 java.lang.RuntimeException: Unable to start activity ComponentInfo{n18.a0.x5.debug.debug/hx520.hxhx.main.MainTabNew}: android.support.v4.app.Fragment$InstantiationException: Unable to instantiate fragment com.dmcapps.navigationfragment.manager.SingleStackNavigationManagerFragment: make sure class name exists, is public, and has an empty constructor that is public
```

reproducing it:
1. goto developer settings and turn on DONT KEEP ACTIVITY.
2. trigger stateloss by minimizing it or open other apps.
3. reopen this app.

resurface on:
- 0.2.0.2
- 0.2.0.1

**Comment by DMCApps** [comment]
Version 0.2.0.3 with this hotfix is now live. Please update your dependencies

**Comment by jjhesk** [comment]
thank you for the quick fix.. im going to give it a try tonight..

**Comment by DMCApps** [comment]
Thanks @jjhesk! Let me know if there's any other issues arising! I'll gladly help you out!

Also I'm looking to put more work into the library so any more enhancements please just let me know!
