### ISSUE TITLE
animation shared element transition on api LOLLIPOP

### ISSUE THREAD

**Issue by jjhesk** [DMCApps/NavigationFragment#27]
There is a missing transition when callling shared element transition.
For example, when it is calling from another fragment or navigationfragment object when the followings:

``` java
     final Pair<View, String>[] pairs = TransitionHelper.createSafeTransitionParticipants(
                            getActivity(),
                            false,
                            new Pair<>(c, "transitionname"));
                    ActivityOptionsCompat transitionActivityOptions = ActivityOptionsCompat.makeSceneTransitionAnimation(getActivity(), pairs);
                    startActivity(target, transitionActivityOptions.toBundle());

```

with another fragment.. 

``` java
Transition transition = TransitionInflater.from(getContext()).inflateTransition(R.transition.my_transition);
        getActivity().getWindow().setSharedElementEnterTransition(transition);
        transition.addListener(new Transition.TransitionListener() {

...

```

Are there any plans to implement transition support this?

**Comment by DMCApps** [comment]
@jjhesk I've never worked with these types of animations. The most I've used are animations from the anim resource folder and ObjectAnimator. Can you elaborate on how you would apply them to the presentation of a Fragment or lead me to some resources on how they are used?

I'm currently working on a non-support version of the navigation manager so there are a lot of changes that it is undergoing. Once I've completed that I can see how to implement these types of transitions between fragments.

**Comment by jjhesk** [comment]
ok.  can i add some pr on the sample app. that will illustrate the shared element transitions on top of the navifragments.

**Comment by DMCApps** [comment]
Please make sure to add the sample to the dev branch. That is where I like to keep all the in progress development!

Thanks very much for your patience and continued support!

**Comment by DMCApps** [comment]
@jjhesk Yeah add an example for me and I'll get around to it when I get a chance. 

Thanks for the continued support and patience

**Comment by jjhesk** [comment]
@DMCApps  I found this [library](https://github.com/vikramkakkar/ImageTransition) that can give you an idea how this work.

**Comment by DMCApps** [comment]
alright thanks @jjhesk! Not sure I'll have a chance to look at this for a while, but I'll let you know when I'm in progress for it!

**Comment by jjhesk** [comment]
if u got some time still, you may take a look of their architecture. Im currently using 90% of the base fragment extended from navigationfragment. [Detail of the sample](https://github.com/zhangke3016/TranslationCompat)

**Comment by DMCApps** [comment]
this is complete in the 2.0.0 version. Please check the ReadMe for migration notes
