### ISSUE TITLE
StackManager.popFragment() Implementation Causing Back Button Issue

### ISSUE THREAD

**Issue by jackcsk** [DMCApps/NavigationFragment#29]
When the `navigationFragment.dismissFragment()` is called at the root stack, can I prevent it from calling getActivity().onBackPressed()?
It is related to cases that we will pop the fragment when the app fails to load data from server, and it is causing issue of exiting the app if the `dismissFragment()` call is triggered at the root.

**Comment by jackcsk** [comment]
@DMCApps: never mind, I can check it with `getNavigationManager().isOnRootFragment()`
Thanks. :-)

**Comment by DMCApps** [comment]
@jackcsk Not a problem! Glad to see you're still enjoying the library!
